#!/bin/zsh

echo removing existing imagemagick source
rm -rf ./.tmp
mkdir .tmp

IMAGEMAGICK_VERSION=7.1.1-11

echo downloading imagemagick release ${IMAGEMAGICK_VERSION}
curl https://imagemagick.org/archive/releases/ImageMagick-${IMAGEMAGICK_VERSION}.tar.xz -o ./.tmp/ImageMagick.tar.gz
tar -xf .tmp/ImageMagick.tar.gz -C ./.tmp

TARGET_DIR=src/main/cpp/imagemagick
rm -fr ${TARGET_DIR}

echo Copying imagemagick code to ${TARGET_DIR}

mkdir ${TARGET_DIR}
mkdir ${TARGET_DIR}/include

# copy to generated dir
for SOURCE_DIR in "MagickCore" "MagickWand" "coders"
do
    # copy impl
    mkdir ${TARGET_DIR}/${SOURCE_DIR}
    cp .tmp/ImageMagick-${IMAGEMAGICK_VERSION}/${SOURCE_DIR}/*.c ${TARGET_DIR}/${SOURCE_DIR}
    # copy headers
    mkdir ${TARGET_DIR}/include/${SOURCE_DIR}
    cp .tmp/ImageMagick-${IMAGEMAGICK_VERSION}/${SOURCE_DIR}/*.h ${TARGET_DIR}/include/${SOURCE_DIR}
done

mkdir ${TARGET_DIR}/Magick++
mkdir ${TARGET_DIR}/include/Magick++
cp .tmp/ImageMagick-${IMAGEMAGICK_VERSION}/Magick++/lib/*.cpp ${TARGET_DIR}/Magick++
cp .tmp/ImageMagick-${IMAGEMAGICK_VERSION}/Magick++/lib/Magick++/* ${TARGET_DIR}/include/Magick++
cp .tmp/ImageMagick-${IMAGEMAGICK_VERSION}/Magick++/lib/Magick++.h ${TARGET_DIR}/include/Magick++

# copy coders private h file, usually generated by configure
cp .tmp/ImageMagick-${IMAGEMAGICK_VERSION}/coders/psd-private.h ${TARGET_DIR}/coders

# copy impl file for filters (no headers)
mkdir ${TARGET_DIR}/filters
cp .tmp/ImageMagick-${IMAGEMAGICK_VERSION}/filters/*.c ${TARGET_DIR}/filters

# modify generated config to match system config
CONFIG_VALUE_OVERRIDES=(
        "MAGICKCORE_X11_DELEGATE"
        "MAGICKCORE_HAVE_SYS_SENDFILE_H"
        "MAGICKCORE_WEBP_DELEGATE"
        "MAGICKCORE_FONTCONFIG_DELEGATE"
        "MAGICKCORE_FREETYPE_DELEGATE"
        "MAGICKCORE_HAVE_TIFFCONF_H"
        "MAGICKCORE_TIFF_DELEGATE"
        "MAGICKCORE_LCMS_DELEGATE"
        "MAGICKCORE_PANGOCAIRO_DELEGATE"
        "MAGICKCORE_LZMA_DELEGATE"
        "MAGICKCORE_HAVE_POSIX_FALLOCATE"
        "MAGICKCORE_HAVE_NEWLOCALE"
        "MAGICKCORE_LIBOPENJP2_DELEGATE"
        "MAGICKCORE_HAVE_STDLIB_H"
        "MAGICKCORE_DJVU_DELEGATE"
        "MAGICKCORE_RAW_R_DELEGATE"
        "MAGICKCORE_RAQM_DELEGATE"
        "MAGICKCORE_OPENEXR_DELEGATE"
        "MAGICKCORE_BZLIB_DELEGATE"
        "MAGICKCORE_HAVE_GETENTROPY"
        "MAGICKCORE_ZLIB_DELEGATE"
        "MAGICKCORE_HAVE_SIGACTION"
        "MAGICKCORE_THREAD_SUPPORT"
        "MAGICKCORE_HAVE_GETDTABLESIZE"
        "MAGICKCORE_HAVE_STRINGS_H"
        "MAGICKCORE_XML_DELEGATE"
        "MAGICKCORE_JXL_DELEGATE"
)
for CONFIG_VALUE in $CONFIG_VALUE_OVERRIDES; do
    sed -i "" "s|#define ${CONFIG_VALUE}|//&|g" src/main/cpp/imagemagick/include/MagickCore/magick-baseconfig.h
done

sed -i "" "s/#define MAGICKCORE_DISTRIBUTE_CACHE_H/&\n#define LENGTH_TYPE int\n#define CLOSE_SOCKET(socket)/" src/main/cpp/imagemagick/include/MagickCore/distribute-cache.h

rm -rf ./.tmp

echo Update complete
